# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c6b84fd47f56492c6d2eb885362f9de643f5be411f50b8fc1fa59775905db4ed31fe0bb19eb675dd63f4223b0dd51878557ac28c5c440e56b7bddc21a14f24ec

test:
  secret_key_base: 36096a2c65304a10604233bea2cbaed9aaae7bfbd3771fc7653c1aaba6fef1442ce82ef3155e48f4af6b1c3aac5087008c3ae43e935b567c588a471f813ad042

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
